/*
 * User API
 *
 * An API for creating and authenticating system users
 *
 * API version: 0.1.0
 * Contact: joe@bebo.dev
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

type UserCredentials struct {

	// the username of an account
	Username string `json:"username"`

	// the password of an account
	Password string `json:"password"`
}
