/*
 * User API
 *
 * An API for creating and authenticating system users
 *
 * API version: 0.1.0
 * Contact: joe@bebo.dev
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

type ExistingUserAccount struct {

	// the id of an account
	Id int32 `json:"id"`

	// describes whether an account was authenticated
	Authenticated bool `json:"authenticated"`
}
